library(shiny)
library(fpp3)
library(plotly)

climate <- read.csv("DailyDelhiClimate.csv")

ui <- fluidPage(
  checkboxGroupInput(inputId = "selected_year", 
                     label = "Year", 
                     selected = 2015,
                     choices = sort(unique(year(climate$date)))),
  
  # using radio button with above table output - to give summary for one of 4 col variable
  radioButtons("summary_selection", label = h3("Summary"),
               choices = list("Temp" = "meantemp", 
                              "Humidity" = "humidity", 
                              "Wind Speed" = "wind_speed", 
                              "Pressure" = "meanpressure"), 
               selected = "humidity"),
  
  plotOutput("climate_plot"),
  
  verbatimTextOutput("summary_table")
)

server <- function(input, output, session) {
  
  # Render the climate plot
  output$climate_plot <- renderPlot({
    filtered_data <- climate %>%
      mutate(date = as.Date(date)) %>%
      tsibble(index = date) %>% 
      filter(year(date) %in% input$selected_year) 
    
    plot_data <- filtered_data[, c("date", input$summary_selection)]
    #autoplot(plot_data)
    
    # using ggplot to avoid warnings generated by autoplot()
    ggplot(plot_data, aes(x = date, y = !!sym(input$summary_selection))) +
      geom_line() + 
      ggtitle(paste("Plot and Summary of", input$summary_selection)) +
      theme(plot.title = element_text(hjust = 0.5, size = 16, face = "bold"))
  })
  
  # Render the summary table
  output$summary_table <- renderPrint({
    climate_summary <- climate %>%
      mutate(date = as.Date(date)) %>%
      tsibble(index = date) %>% 
      filter(year(date) %in% input$selected_year)
    
    climate_summary <- as.data.frame(climate_summary[[input$summary_selection]])
    print(summary(climate_summary))
  })
}

shinyApp(ui, server)






